# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hmensah- <hmensah-@student.42abudhabi.a    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/02/21 18:06:33 by hmensah-          #+#    #+#              #
#    Updated: 2025/02/21 22:41:26 by hmensah-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		= pipex
CC			= cc
ARGS		= -Wall -Werror -Wextra
RM			= rm -f

SRCS		= parser.c pipex.c

OBJS		= $(SRCS:.c=.o)

LIBFT_DIR	= ./libft

